name: ExpSign
main: com.Nepian.ExpSign.ExpSign
version: 0.1
author: Nepian
depend:
- Vault
permissions:
  ExpSign.admin:
  ExpSign.shop.create.buy:
  ExpSign.shop.create.sell:
  ExpSign.shop.buy:
  ExpSign.shop.sell: